import { Nanum_Gothic } from 'next/font/google';
import './globals.css';

const gothic = Nanum_Gothic({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={gothic.className}>
      <body>{children}</body>
    </html>
  );
}
